config/routes.rb
Rails.application.routes.draw do
  resources :statements
  devise_for :customers
  get 'up' => 'rails/health#show', as: :rails_health_check

  root 'statements#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
# frozen_string_literal: true

class Customer < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :statements

  def this_month_statements
    statements.where(
      'created_at > ? AND created_at < ?',
      Time.now.beginning_of_month, Time.now.end_of_month
    )
  end

  def current_month_disposable_income
    statement_rating_for_customer[:disposable_income]
  end

  def current_month_ie_band
    statement_rating_for_customer[:ie_band]
  end

  private

  def statement_rating_for_customer
    @statement_rating_for_customer ||= StatementRatingCalculatorService.call(
      this_month_statements.map(&:statement_items).flatten
    )
  end
end

app/models/statement.rb
# frozen_string_literal: true

class Statement < ApplicationRecord
  belongs_to :customer
  has_many :statement_items, dependent: :delete_all
  accepts_nested_attributes_for :statement_items, allow_destroy: true,
                                                  reject_if: :destroy_marked?

  validates_presence_of :customer

  private

  def destroy_marked?(attributes)
    attributes['_destroy'] == '1'
  end
end

app/models/statement_item.rb
# frozen_string_literal: true

class StatementItem < ApplicationRecord
  belongs_to :statement

  validates_presence_of :statement, :title, :amount, :transaction_type

  after_commit :update_statement

  private

  def update_statement
    res = StatementRatingCalculatorService.call(statement.statement_items)

    statement.update(
      disposable_income: res[:disposable_income],
      ie_rating: res[:ie_band]
    )
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_customer!
end

app/controllers/statements_controller.rb
# frozen_string_literal: true

class StatementsController < ApplicationController
  before_action :set_statement, only: %i[show edit update destroy]

  def index
    @statements = current_customer.this_month_statements
  end

  def show; end

  def new
    @statement = Statement.new
    @statement.statement_items.build
  end

  def edit; end

  def create
    @statement = Statement.new(statement_params)

    respond_to do |format|
      if @statement.save
        format.html do
          redirect_to statement_url(@statement),
                      notice: 'Statement was successfully created.'
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @statement.update(statement_params)
        format.html do
          redirect_to statement_url(@statement),
                      notice: 'Statement was successfully updated.'
        end
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @statement.destroy!

    respond_to do |format|
      format.html do
        redirect_to statements_url,
                    notice: 'Statement was successfully destroyed.'
      end
    end
  end

  private

  def set_statement
    @statement = current_customer.statements.find(params[:id])
  end

  def statement_params
    params.require(:statement).permit(
      :customer_id, statement_items_attributes: %i[
        id title amount transaction_type _destroy
      ]
    )
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/statements_helper.rb
# frozen_string_literal: true

module StatementsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>I&E</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'https://code.jquery.com/jquery-3.6.0.min.js', 'statements' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" integrity="..." crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/statements/_form.html.erb
<%= form_with(model: statement, class: 'my-4') do |form| %>
  <% if statement.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(statement.errors.count, "error") %> prohibited this statement from being saved:</h2>

      <ul>
        <% statement.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div id="statement_items">
    <%= form.fields_for :statement_items, @statement.statement_items || @statement.statement_items.build do |si| %>
      <%= render 'statement_item_fields', f: si %>
      <%= si.hidden_field :id %>
    <% end %>
  </div>

  <div id="add_statement_item" class="mb-3">
    <%= link_to 'Add Statement Item', '#', id: 'add_statement_item_link', class: 'btn btn-primary' %>
  </div>

  <div class="mb-3">
    <%= form.hidden_field :customer_id, value: current_customer.id %>
  </div>

  <div>
    <%= form.submit 'Save Statement', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/statements/_statement.html.erb
<div id="<%= dom_id statement %>" class="container mt-4">
  <p class="mb-2">
    <strong>Disposable income:</strong>
    £<%= statement.disposable_income %>
  </p>

  <p class="mb-2">
    <strong>Ie rating:</strong>
    <%= statement.ie_rating %>
  </p>

  <p class="mb-2">
    <strong>Customer:</strong>
    <%= statement.customer.email %>
  </p>

  <p class="mb-2">
    <strong>Creation date:</strong>
    <%= statement.created_at %>
  </p>

  <% if @statement&.statement_items.blank? %>
    <p class="mb-2">No statement items...</p>
  <% else %>
    <div class="row">
      <div class="col">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>Income</th>
              <th>Amount</th>
            </tr>
          </thead>
          <tbody>
            <% @statement.statement_items.select { |i| i.transaction_type == 'income' }.each do |item| %>
              <tr>
                <td><%= item.title %></td>
                <td>£<%= item.amount %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      <div class="col">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>Expenditure</th>
              <th>Amount</th>
            </tr>
          </thead>
          <tbody>
            <% @statement.statement_items.select { |i| i.transaction_type == 'expenditure' }.each do |item| %>
              <tr>
                <td><%= item.title %></td>
                <td>£<%= item.amount %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  <% end %>
</div>

app/views/statements/_statement_item_fields.html.erb
<div class="nested-fields">
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :amount %>
  <%= f.number_field :amount %>
  <%= f.label :transaction_type %>
  <%= f.select :transaction_type, options_for_select(['income', 'expenditure'], f.object.transaction_type) %>
  <%= f.hidden_field :id %>
  <%= f.label 'Remove item' %>
  <%= f.check_box :_destroy, class: 'remove-item' %>
</div>

app/views/statements/edit.html.erb
<div class="container mt-4">
  <h1 class="mb-4">Editing statement</h1>

  <div class="mb-4">
    <%= link_to "Back to statements", statements_path, class: "btn btn-secondary mr-2" %>
    <%= link_to "Show this statement", @statement, class: "btn btn-primary" %>
  </div>

  <%= render "form", statement: @statement %>

  <br>
</div>

app/views/statements/index.html.erb
<div class="container mt-4">
  <p class="text-success"><%= notice %></p>

  <h1 class="mb-4">My Statements</h1>
  <h2><%= Date.today.strftime("%B") %></h2>

  <div class="row mt-4">
    <div class="col">
      <h3>This month's total Disposable Income</h3>
      <h4>£<%= current_customer.current_month_disposable_income %></h4>
    </div>
    <div class="col">
      <h3>This month's total I&E Band</h3>
      <h4><%= current_customer.current_month_ie_band %></h4>
    </div>
  </div>

  <%= link_to "New statement", new_statement_path, class: "btn btn-primary mt-4" %>

  <div id="statements" class="mt-4">
    <% if @statements.blank? %>
      <p>No statements filed yet.</p>
    <% else %>
      <table class="table">
        <thead>
          <tr>
            <th>Date Of Creation</th>
            <th>I&E Rating</th>
            <th>Disposable Income</th>
            <th>View Details</th>
          </tr>
        </thead>
        <tbody>
          <% @statements.each do |statement| %>
            <tr>
              <td><%= statement.created_at %></td>
              <td><%= statement.ie_rating %></td>
              <td>£<%= statement.disposable_income %></td>
              <td>
                <%= link_to '👀', statement_path(statement), class: "btn btn-outline-secondary" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

app/views/statements/new.html.erb
<div class="container">
  <h1 class="display-4">New Statement</h1>

  <%= render "form", statement: @statement %>

  <br>

  <div class="mt-4">
    <%= link_to "Back to Statements", statements_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/statements/show.html.erb
<div class="container mt-4">
  <p class="text-success"><%= notice %></p>

  <%= link_to "Back to statements", statements_path, class: "btn btn-outline-primary mb-4" %>

  <%= render @statement %>

  <div class="mt-4">
    <%= link_to "Edit", edit_statement_path(@statement), class: "btn btn-warning mr-2" %>
    <%= button_to "Delete", @statement, method: :delete, data: { confirm: "Are you sure you want to delete this statement?" }, class: "btn btn-danger", form_class: "d-inline" %>
  </div>
</div>